// =============================================================================
// jtag_if.sv
// Bit-bang JTAG driver for riscv-dbg's dmi_jtag_tap (debug spec 0.13).
//
// Verified against the actual RTL in this repo:
//   - dmi_jtag_tap.sv : IrLength=5, IDCODE=5'h01, DTMCSR=5'h10, DMIACCESS=5'h11
//                       shift registers are right-shift, new bit -> MSB,
//                       output = current LSB (i.e. classic LSB-first shift).
//   - dmi_jtag.sv      : dtmcs/dmi shift registers use the same {tdi, q>>1}
//                       pattern -> LSB-first also applies to DTMCS/DMI DR.
//   - dm_pkg.sv        : dm_csr_e register map, dmi_req_t = {addr[6:0],
//                       op[1:0], data[31:0]} packed MSB->LSB i.e. bit 40
//                       downto 0 = {addr,op,data}... NOTE: dm_pkg packs it
//                       as addr(7):op(2):data(32) high->low, so as a raw
//                       41-bit scan word bit[0] is data[0], bit[33] is op[0],
//                       bit[34] is addr[0]. We build/parse the scan word
//                       explicitly below rather than relying on the struct,
//                       since DR shifting is bit-serial over the pads only.
//
// Usage: hook tck/tms/tdi/tdo/trst_n to the DUT's jtag_* pins and call the
// tasks below from your test sequence. All tasks are `automatic`/blocking
// and self-contained (no clocking block needed) so this works fine when TCK
// is generated by the driver itself, async to the core clock.
// =============================================================================

interface jtag_if;

  logic tck;
  logic tms;
  logic tdi;
  logic tdo;
  logic trst_n;

  // TCK half-period. Keep this comfortably slower than the core clock so the
  // dmi_cdc (TCK <-> core clk domain crossing) has time to settle. Override
  // via `defparam`/hierarchical force from the tb top if your env needs a
  // different ratio.
  time tck_half_period = 20ns; // 25 MHz JTAG clk assuming core clk ~100MHz+

  // ---------------------------------------------------------------------
  // Low level: one JTAG clock edge pair, TMS/TDI driven before the rising
  // edge (state transition happens here), TDO sampled after the falling
  // edge (dmi_jtag_tap's TDO register is clocked off the inverted TCK).
  // ---------------------------------------------------------------------
  task automatic tck_pulse(input logic tms_val, input logic tdi_val, output logic tdo_val);
    tms = tms_val;
    tdi = tdi_val;
    #(tck_half_period/2);
    tck = 1'b1;
    #(tck_half_period);
    tdo_val = tdo; // stable well before this point, sampled here for margin
    tck = 1'b0;
    #(tck_half_period/2);
  endtask

  // ---------------------------------------------------------------------
  // TAP reset via TRST_N (async), then park in Run-Test/Idle.
  // ---------------------------------------------------------------------
  task automatic tap_reset();
    logic unused;
    tck    = 1'b0;
    tms    = 1'b1;
    tdi    = 1'b0;
    trst_n = 1'b0;
    #(tck_half_period*5);
    trst_n = 1'b1;
    #(tck_half_period*5);
    // Belt-and-braces: 5x TMS=1 also forces TestLogicReset from any state
    // per JTAG spec, in case some environments tie trst_ni high permanently.
    repeat (5) tck_pulse(1'b1, 1'b0, unused);
    // -> RunTestIdle
    tck_pulse(1'b0, 1'b0, unused);
  endtask

  // Idle for N TCK cycles (e.g. to let an abstract command retire without
  // polling, or to satisfy dtmcs.idle hint cycles).
  task automatic idle_ticks(input int n);
    logic unused;
    repeat (n) tck_pulse(1'b0, 1'b0, unused);
  endtask

  // ---------------------------------------------------------------------
  // IR shift: RunTestIdle -> SelectDR -> SelectIR -> CaptureIR -> ShiftIR
  //           -> Exit1IR -> UpdateIR -> RunTestIdle
  // 5-bit IR, shifted LSB-first (ir[0] first).
  // ---------------------------------------------------------------------
  task automatic shift_ir(input logic [4:0] ir);
    logic unused;
    tck_pulse(1'b1, 1'b0, unused); // RunTestIdle    -> SelectDrScan
    tck_pulse(1'b1, 1'b0, unused); // SelectDrScan   -> SelectIrScan
    tck_pulse(1'b0, 1'b0, unused); // SelectIrScan   -> CaptureIr
    tck_pulse(1'b0, 1'b0, unused); // CaptureIr      -> ShiftIr
    for (int i = 0; i < 5; i++) begin
      // last bit must assert TMS=1 to move to Exit1Ir
      tck_pulse((i == 4), ir[i], unused);
    end
    tck_pulse(1'b1, 1'b0, unused); // Exit1Ir -> UpdateIr
    tck_pulse(1'b0, 1'b0, unused); // UpdateIr -> RunTestIdle
  endtask

  // ---------------------------------------------------------------------
  // DR shift: RunTestIdle -> SelectDR -> CaptureDR -> ShiftDR -> Exit1DR
  //           -> UpdateDR -> RunTestIdle
  // `nbits`-wide, shifted LSB-first both directions.
  // Max 64 bits (plenty; DMI is 41 bits, DTMCS/IDCODE are 32).
  // ---------------------------------------------------------------------
  task automatic shift_dr(input int nbits, input logic [63:0] wdata, output logic [63:0] rdata);
    logic bit_out;
    rdata = '0;
    tck_pulse(1'b1, 1'b0, bit_out); // RunTestIdle -> SelectDrScan
    tck_pulse(1'b0, 1'b0, bit_out); // SelectDrScan -> CaptureDr
    tck_pulse(1'b0, 1'b0, bit_out); // CaptureDr -> ShiftDr
    for (int i = 0; i < nbits; i++) begin
      tck_pulse((i == nbits-1), wdata[i], bit_out);
      rdata[i] = bit_out;
    end
    tck_pulse(1'b1, 1'b0, bit_out); // Exit1Dr -> UpdateDr
    tck_pulse(1'b0, 1'b0, bit_out); // UpdateDr -> RunTestIdle
  endtask

  // ---------------------------------------------------------------------
  // DTM-level constants (IR opcodes / dm_csr fields), mirrored from
  // dmi_jtag_tap.sv / dm_pkg.sv so this file has no compile dependency on
  // the DUT package (keeps the BFM portable across environments).
  // ---------------------------------------------------------------------
  localparam logic [4:0] IR_BYPASS   = 5'h00;
  localparam logic [4:0] IR_IDCODE   = 5'h01;
  localparam logic [4:0] IR_DTMCSR   = 5'h10;
  localparam logic [4:0] IR_DMIACCESS = 5'h11;

  localparam logic [1:0] DTM_NOP   = 2'b00;
  localparam logic [1:0] DTM_READ  = 2'b01;
  localparam logic [1:0] DTM_WRITE = 2'b10;

  localparam logic [1:0] DTM_SUCCESS = 2'b00;
  localparam logic [1:0] DTM_ERR     = 2'b10;
  localparam logic [1:0] DTM_BUSY    = 2'b11;

  // ---------------------------------------------------------------------
  // read_idcode(): IR=IDCODE, shift 32-bit DR of all zero, capture value.
  // ---------------------------------------------------------------------
  task automatic read_idcode(output logic [31:0] idcode);
    logic [63:0] rd;
    shift_ir(IR_IDCODE);
    shift_dr(32, 64'h0, rd);
    idcode = rd[31:0];
  endtask

  // ---------------------------------------------------------------------
  // DTMCS access: IR=DTMCSR, 32-bit DR.
  // dtmcs bit layout (dm_pkg::dtmcs_t, LSB->MSB): version[3:0], abits[9:4],
  // dmistat[11:10], idle[14:12], zero0, dmireset[16], dmihardreset[17].
  // ---------------------------------------------------------------------
  task automatic read_dtmcs(output logic [31:0] dtmcs);
    logic [63:0] rd;
    shift_ir(IR_DTMCSR);
    shift_dr(32, 64'h0, rd);
    dtmcs = rd[31:0];
  endtask

  // dmireset: clears the sticky DMI 'op' error (DTM_ERR) without touching
  // the DM itself. dmihardreset: also resets dm_top's DMI-facing state via
  // dmi_rst_no (see soc_top's dmi_rst_n wiring).
  task automatic dtmcs_reset(input bit hard_reset);
    logic [63:0] wr, rd;
    wr = '0;
    wr[16] = 1'b1;          // dmireset
    wr[17] = hard_reset;    // dmihardreset
    shift_ir(IR_DTMCSR);
    shift_dr(32, wr, rd);
  endtask

  // ---------------------------------------------------------------------
  // Raw DMI op: IR=DMIACCESS, 41-bit DR = {addr[6:0], data[31:0], op[1:0]}
  // scanned LSB-first (op bits go in/out first). Returns the *previous*
  // operation's result per spec (result of THIS op is visible on the next
  // scan) -- callers should use dmi_write/dmi_read which handle this.
  // ---------------------------------------------------------------------
  task automatic dmi_scan(input logic [6:0] addr, input logic [31:0] data,
                          input logic [1:0] op,
                          output logic [31:0] rdata, output logic [1:0] resp);
    logic [63:0] wr, rd;
    wr = '0;
    wr[1:0]   = op;
    wr[33:2]  = data;
    wr[40:34] = addr;
    shift_ir(IR_DMIACCESS);
    shift_dr(41, wr, rd);
    resp  = rd[1:0];
    rdata = rd[33:2];
  endtask

  // dmi_write/dmi_read: perform the op, then issue a NOP scan to retrieve
  // the result (per spec, result of an op is only guaranteed valid on the
  // *next* DMI scan). Retries with dmireset on DTM_BUSY, capped so a real
  // bug shows up as a test failure instead of hanging the sim.
  task automatic dmi_write(input logic [6:0] addr, input logic [31:0] data);
    logic [31:0] rdata;
    logic [1:0]  resp;
    int          tries;
    tries = 0;
    do begin
      dmi_scan(addr, data, DTM_WRITE, rdata, resp); // issue write
      dmi_scan(7'h0, 32'h0, DTM_NOP, rdata, resp);   // NOP -> read back status
      if (resp == DTM_BUSY) begin
        dtmcs_reset(1'b0);
        tries++;
      end
    end while (resp == DTM_BUSY && tries < 50);
    if (resp != DTM_SUCCESS)
      $error("[JTAG] dmi_write(addr=0x%0h,data=0x%0h) failed, resp=%0d (tries=%0d)",
             addr, data, resp, tries);
  endtask

  task automatic dmi_read(input logic [6:0] addr, output logic [31:0] data);
    logic [31:0] rdata;
    logic [1:0]  resp;
    int          tries;
    tries = 0;
    do begin
      dmi_scan(addr, 32'h0, DTM_READ, rdata, resp); // issue read
      dmi_scan(7'h0, 32'h0, DTM_NOP,  rdata, resp); // NOP -> get the data
      if (resp == DTM_BUSY) begin
        dtmcs_reset(1'b0);
        tries++;
      end
    end while (resp == DTM_BUSY && tries < 50);
    if (resp != DTM_SUCCESS)
      $error("[JTAG] dmi_read(addr=0x%0h) failed, resp=%0d (tries=%0d)", addr, resp, tries);
    data = rdata;
  endtask

endinterface : jtag_if
